# Generated by Django 5.2.9 on 2025-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_recognition", "0002_alter_uploadedimage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="emotion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="emotion_conf",
            field=models.FloatField(default=0.0),
        ),
    ]
